version: 2

sources:
  - name: raw
    database: ee-india-se-data
    schema: movies_data_ajit
    tables:
      - name: movies_raw
      - name: ratings_raw 
models:
  - name: movie_ratings_pres
    columns:
      - name: movie_id
        data_type: INT
        data_tests:
          - not_null
          - relationships:
              to: ref("movies_raw_to_curate")
              field: id
      - name:  ratings
        data_type: DECIMAL
        data_test:
          - not_null
      - name: number_of_ratings
        data_type: INT
      - name: median_ratings
        data_type: DECIMAL
      - name: rank_movie_by_median_rating
        data_type: DECIMAL



  - name: ratings_raw_to_curate
    description: "A dbt model on Curate layer for Ratings"
    columns:
      - name: userId
        data_type: INT
        data_tests:
          - not_null

      - name: movieId
        data_type: INT

      - name: rating
        data_type: DECIMAL

      - name: timestamp
        data_type: TIMESTAMP
      
      - name: load_time
        data_type: DATETIME

  - name: movies_raw_to_curate
    description: "A Movies Curate dbt model from raw"
    columns:
      - name: adult
        data_type: boolean
        description: ""

      - name: belongs_to_collection
        data_type: json
        description: ""

      - name: budget
        data_type: int64
        description: ""

      - name: genres
        data_type: string
        description: ""

      - name: homepage
        data_type: string
        description: ""

      - name: id
        description: "The primary key for this table"
        data_tests:
          - not_null
        data_type: int64
        description: ""

      - name: imdb_id
        data_type: string
        description: ""

      - name: original_language
        data_type: string
        description: ""

      - name: original_title
        data_type: string
        description: ""

      - name: overview
        data_type: string
        description: ""

      - name: popularity
        data_type: numeric
        description: ""

      - name: poster_path
        data_type: string
        description: ""
        data_tests:
          - starts_with:
              prefix: "/"

      - name: production_companies
        data_type: string
        description: ""

      - name: production_countries
        data_type: string
        description: ""

      - name: release_date
        data_type: date
        description: ""

      - name: revenue
        data_type: int64
        description: ""

      - name: runtime
        data_type: numeric
        description: ""

      - name: spoken_languages
        data_type: string
        description: ""

      - name: status
        data_type: string
        description: ""

      - name: tagline
        data_type: string
        description: ""

      - name: title
        data_type: string
        description: ""

      - name: video
        data_type: boolean
        description: ""

      - name: vote_average
        data_type: numeric
        description: ""

      - name: vote_count
        data_type: int64
        description: ""

      - name: load_date
        data_type: datetime
        description: ""



