# This workflow will deploy source code on Cloud Run when a commit is pushed to the "main" branch

name: Deploy to Cloud Function from Source

on: [push]
  # push:
    # branches: [ "main" ]
on: [push]
  # push:
    # branches: [ "main" ]

env:
  PROJECT_ID: ee-india-se-data # TODO: update Google Cloud project id
  SERVICE: se-data-india-service-account # TODO: update Cloud Run service name
  REGION: asia-south1 # TODO: update Cloud Run service region
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.8
          #   terraform_wrapper: false
      - name: Terraform fmt
        id: fmt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run:  terraform init 
      
      # Run a terraform plan for pull requests only
      - name: Terraform Plan
        id: plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
      
        # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        if: github.event_name == 'push'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: terraform apply -auto-approve
